domain: YuchanYan.com
baseurl: "/portfolio"
url: "https://catapplesofa.github.io"

title: Yuchan Yan
email: angela10547@163.com
author: Yuchan Yan

lang: en

plugins:
  - jekyll-seo-tag

color: "#13ccf9"
# disqus:
#   shortname: example-com
#
rrss:
  email: "angela10547@163.com"
  telegram: "https://t.me/"
  discord: "https://discord.com/"
  linkedin: "https://www.linkedin.com/in/angela-yan-1a40a92b0/"

header_pages:
  - index.md       # your homepage
  # - portfolio.md   # your portfolio page
